### ISSUE TITLE
Confidence intervals of bivariate smooths

### ISSUE THREAD

**Issue by gavinsimpson** [gavinsimpson/gratia#1]
_From @scottkosty on April 6, 2018 16:30_

This is a feature request for adding support for confidence intervals of bivariate smooths.

In the below example code, there is one call to `confint` that succeeds, but when adding a `newdata` argument or a `type` argument, it fails.

```
library(mgcv)
library(gratia)
set.seed(2)
dat <- gamSim(2, n = 4000, dist = "normal", scale = 1)
m2 <- gam(y ~ s(x, z, k = 30), data = dat$data, method = "REML")

# this works (in the sense of no error)
test1 <- confint(m2, parm = "x,z")

# however, these fail
test2 <- confint(m2, parm = "x,z", type = "simultaneous")
newd_ <- data.frame(x = dat$x, y = dat$y, z = dat$z)
test3 <- confint(m2, parm = "x,z", newdata = newd_)

# I'm guessing these are not expected to work, but I tried them just in case,
# and they do not succeed:

# since there is only one smooth, I thought I could exclude the parm
test4 <- confint(m2, newdata = newd_)
test5 <- confint(m2, type = "simultaneous")

# try specifying parm with s()
test6 <- confint(m2, parm = "s(x,z)", newdata = newd_)
test7 <- confint(m2, parm = "s(x,z)", type = "simultaneous")

# try specifying parm with number
test8 <- confint(m2, parm = 1, newdata = newd_)
test9 <- confint(m2, parm = 1, type = "simultaneous")
```

_Copied from original issue: gavinsimpson/schoenberg#3_

**Comment by raff-k** [comment]
If in [`confint-methods.R`  line 251](https://github.com/gavinsimpson/gratia/blob/f5ce2b9004cee386f85c98a297e03b573558cf39/R/confint-methods.R#L251)  `S <- S[d <= 1L]` is changed to `S <- S[d <= 2L]` than in `evaluate_smooth` the function `evaluate_2d_smooth` is called for the bivariate smooth; thus one receive the critical value for a bivariate smooth.

**Comment by psychobas** [comment]
Hi, thanks for the great package! Is it possible to show significance in draws of 2D smooths (e.g., linetype differs depending on whether the estimates are significant or not)?

Here is an example of what I mean based on the example data you provided above:
```
library(mgcv)
library(schoenberg)
set.seed(2)
dat <- gamSim(2, n = 4000, dist = "normal", scale = 1)
m2 <- gam(y ~ s(x, z, k = 30), data = dat$data, method = "REML")

test1 <- confint(m2, parm = "x,z", partial_match = TRUE)

test1 %>%
  mutate(sig = (lower < 0 & upper < 0) | (lower > 0 & upper > 0)) %>%
  ggplot(aes(x = x, y = z, fill = est)) + 
  geom_raster(aes(alpha = sig)) + 
  geom_contour(aes(z = est, linetype = sig)) +
  scale_alpha_manual(values = c("TRUE" = 1, "FALSE" = 0.7)) +
  scale_fill_distiller(palette = "RdBu", type = "div")
```

![image](https://github.com/gavinsimpson/gratia/assets/44177662/55d64a47-e61a-4acd-8aa0-0f1ace3dfb7b)


This looks identical to `draw(m2, rug = FALSE)` but with the linetype varying by whether the estimates are significant or not. 

![image](https://github.com/gavinsimpson/gratia/assets/44177662/f6e6038e-c6dc-4643-a7fa-9cc10d82e7eb)

I could use this workaround but it would be great if this would be possible in gratia to not loose the other features provided by `gratia::draw`.

**Comment by gavinsimpson** [comment]
This is an old feature request from the days before gratia was even a thing and has been fixed for almost as long as it has. I will close this an continue the issue about showing confidence intervals in a separate issue: #252
