### ISSUE TITLE
Handle models fitted using mgcv::bam()

### ISSUE THREAD

**Issue by gavinsimpson** [gavinsimpson/gratia#10]
There are currently no specific methods for GAMs estimated using `bam()`. Need to run tests of functionality for `bam()` models and add specific methods or functions where special handling of the model objects is needed.

**Comment by Excidion** [comment]
Since I think my issue relates to this, I will just leave it here: 
Stumbled into this error while trying `datagen()` on a GAM trained with `bam()`:
```
Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match
```

**Comment by gavinsimpson** [comment]
@Excidion would you mind sharing the bam() call you used to fit the model?

**Comment by Excidion** [comment]
```R
model = bam(
  formula = f,
  family = binomial(link = "logit"),
  data = data,
  method = "GACV.Cp",
  knots = knots_list,
  select = TRUE, 
  drop.intercept = FALSE,
  fit = TRUE,
)
```

**Comment by gavinsimpson** [comment]
Thanks (it would help to know what `f` was as well as some `bam()` models work but I don't have tests for all smooth types yet.

**Comment by Excidion** [comment]
The formula `f` ist just lenghty sum of `s(bs='cs', m=2, k=...)` splines of one feature each. Some of them have a factor `by=...` variable set.
The `knots_list` ist exactly that, a list of lists of knots, matching in length with eachs splines `k` values of course.

**Comment by Excidion** [comment]
While working in a similiarly configured GAM i noticed `datagen()` worked on a GAM trained via `bam()`. The configuration is practically identical to the one i provided above. The difference is that the formula object `f` does not include any splines `s()` that have a `by=...` variable set.

**Comment by gavinsimpson** [comment]
Thanks @Excidion. `datagen()` was a bit of a mistake, or at least some of the methods were, and exporting was certainly an error on my part. It was never really intended to do what it claimed, and only ever worked for simple models as you discovered, where all the smooths were of the same order/dimension. As it happens this isn't a `bam` issue.

If a user wants to generate slices of data over which a model is evaluated, then `data_slice()` should be used instead.

In the latest series of commits I turned `datagen()` into an internal function and it is no longer exported from the package namespace. You can still access it using `gratia:::datagen()`, but also note that it's behaviour has been changed such that the `"gam"` method (and hence the for `bam` models too) now will only generate data for a single smooth, the label for which has to be supplied by the user. You can no longer use it to generate data for all smooths in a `gam` model for example.

If `data_slice()` doesn't work for your use case, can you file a new issue specifically for that and I can take a look.

**Comment by gavinsimpson** [comment]
`bam()` fits are handled in general, as they objects it produces inherit from class `"gam"`. Closing this now and I'll open new issues for specific missing functionality if and wen they arise.
