### ISSUE TITLE
Derivatives at the scale of the response

### ISSUE THREAD

**Issue by LisaHuelsmann** [gavinsimpson/gratia#100]
I would like to calculate derivatives of a smoother at the scale of a binomial response, which would allow me to assess the effect of a variable on a probability that I want to compare between different groups. In other words, I want to calculate average marginal effects and corresponding CI (for glm's, I was doing this with the margins package, but now realized that I need more flexibility in the functional form). I thought this could be done with `derivatives()`, but then I realized that so far there is no option to calculate derivatives at the response scale. 

I found your [comment](https://stackoverflow.com/questions/64692046/first-derivative-and-confidence-intervals-from-fitted-gam) on stackoverflow where you say that other users may be interested in this functionality too and thus wanted to ask if you have any updates on this. 

Thanks for the useful package! My discovery of the day!

**Comment by gavinsimpson** [comment]
Hi @LisaHuelsmann 

No developments as yet, but I think I have a very easy way to implement this using existing functionality in {gratia} so I may be able to implement this relatively easily now.

In the mean time, use `fitted_samples()` to generate fitted values on the response scale, and if you supply as `newdata` a data frame containing both the grid of data points you want the derivative for, plus the same shifted by a small amount, so you end up with fitted values on the response scale for x and x_shifted, you can then rearrange the data and diff them to get the response derivatives. The nice thing about doing this using output from `fitted_samples()` is that you can generate the simulations from the posterior that you'll need to calculate an uncertainty interval on the derivative.

**Comment by LisaHuelsmann** [comment]
Hi @gavinsimpson,
thanks a lot for your advice.
In the meantime, I have implemented the marginal effects manually using the linear predictor matrix and simulations from the vcov matrix. But `fitted_samples()` sounds like a neat way to simplify the code. It seems I must have missed this feature while browsing the package... I am glad that your implementation is very similar to what I came up with. I guess `rmvn()` is simply faster than `mvrnorm()`?

**Comment by gavinsimpson** [comment]
Finally got around to implementing this - sorry it took so long. If you want to try it out, you'll need to install the development version (anything from version 0.8.1.10 onward will do) and then look at `?response_derivatives` for an exmaple.

(and yes, `mvnfast::rmvn()` is a more performant interface to sampling from a MVN; you can pass it `n_cores` to distribute the computations over multiple cores for example if you need to generate a lot of samples from a model with lots of coefficients.
