### ISSUE TITLE
Partial derivatives for surfaces

### ISSUE THREAD

**Issue by noamross** [gavinsimpson/gratia#101]
Curious if we could have (partial) derivatives for s(x,y) or similar interaction terms.

**Comment by gavinsimpson** [comment]
By partial derivative do you mean the derivative in `x` holding `y` constant etc?

I have notes on how this is done with finite differences and the more general derivative of x,y, I just need some time to code it up. Might be something I get to between jobs while in quarantine in Denmark later this month.
