### ISSUE TITLE
cannot `draw` a model with multiple `by` smooths with a common continuous term

### ISSUE THREAD

**Issue by StefanoMezzini** [gavinsimpson/gratia#104]
Trying to `draw` a model with two `by` smooths with the same continuous variable gives the error
`Error in .subset2(x, i, exact = exact) : subscript out of bounds`.

Here is a simple example:

``` {r}
library(dplyr)
library(mgcv)
library(gratia)

d <- expand.grid(A = c(0, 1),
                 B = c(0, 1),
                 n = 1:15) %>%
  mutate(x = runif(length(n)),
         y = rnorm(length(n), mean = 3 * x + A * 2 - B),
         A = factor(A), B = factor(B))

gam(y ~ s(x, by = A), data = d) %>% draw() # works
gam(y ~ s(x) + s(x, by = A), data = d) %>% draw() # works
gam(y ~ s(x, by = A) + s(x, by = B), data = d) %>% draw() # doesn't work
```

The issue occurs because the name of the `by` smooth term is changed so that all terms become `s(x)` (see chunk below). This works if there is only one `by` smooth (even in the presence of a global smooth), but it doesn't work if there are multiple `by` smooths.

``` {r}
if (any(is_by)) {
  S <- vapply(strsplit(S, ":"), `[[`, character(1L),
              1L)
}
```

**Comment by atyre2** [comment]
I've been playing around with by variables and prediction today, so this was a helpful example. When I run your example with the current head of master the 2nd model doesn't work and the 3rd one does. However, doing

```r
gam(y ~ s(x) + s(x, by = A), data = d) %>% draw(select = 2:3) # works
```
Telling `gratia` functions which smooths you want by number, rather than the persnickety labels, helps a lot with other problems too.

**Comment by gavinsimpson** [comment]
I'll be taking a look at this shortly; I have just switched to using `smooth_estimates()` internally in `draw.gam()` which likely explains the differences in what works and what doesn't (which I need to look into).

And yes, `smooth_estimates()` has different ways to specify which smooths you want, which wasn't possible when @StefanoMezzini reported this issue.

I had hoped that changing to `smooth_estimates()` would have fixed these issues so it seems I still have a bit of work to do here

**Comment by gavinsimpson** [comment]
All of these are working now; any failures were likely transitory issues as I didn't specifically fix these failures only just made the new code pass all the unit tests.
