### ISSUE TITLE
`dist` argument to `smooth_estimates()` not working

### ISSUE THREAD

**Issue by Aariq** [gavinsimpson/gratia#111]
The `dist` argument in `smooth_estimates()` doesn't seem to do anything, and in the latest development version it doesn't do anything with `draw.gam()` either (but it used to work).  Just checking if you are in the process of removing this feature, of if this is a bug. Here's a reprex using the CRAN version of `gratia`:

``` r
library(mgcv)
#> Loading required package: nlme
#> This is mgcv 1.8-36. For overview type 'help("mgcv-package")'.
library(gratia)
library(ggplot2)

set.seed(1)
#exmple from ?te
test1 <- function(x,z,sx=0.3,sz=0.4) { 
  x <- x*20
  (pi**sx*sz)*(1.2*exp(-(x-0.2)^2/sx^2-(z-0.3)^2/sz^2)+
                 0.8*exp(-(x-0.7)^2/sx^2-(z-0.8)^2/sz^2))
}
n <- 500
x <- runif(n)/20
z <- runif(n)
xs <- seq(0,1,length=30)/20
zs <- seq(0,1,length=30)
pr <- data.frame(x=rep(xs,30),z=rep(zs,rep(30,30)))
truth <- matrix(test1(pr$x,pr$z),30,30)
f <- test1(x,z)
y <- f + rnorm(n)*0.2
b1 <- gam(y~s(x,z))

#with draw.gam()
gratia:::draw.gam(b1, dist = 0.02)
#> Warning: Removed 5459 rows containing non-finite values (stat_contour).
```

![](https://i.imgur.com/iE55gkU.png)

``` r
#with smooth_estimates()
sm_est <- smooth_estimates(b1, dist = 0.02)
ggplot(sm_est, aes(x = x, y = z, z = est, fill = est)) +
  geom_raster()
```

![](https://i.imgur.com/MUmtjmJ.png)

<sup>Created on 2021-08-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by Aariq** [comment]
FWIW, I really liked this feature.  Plotting raw data points is probably better most of the time, but with large amounts of data, the plot gets messy and I prefered the `too.far` / `dist` approach.

**Comment by Aariq** [comment]
Possibly related: in the development version, `draw()` plots 2d smooths with residuals whether or not `residuals = TRUE`.

**Comment by gavinsimpson** [comment]
The `dist` thing is right; the argument is ignored currently. Actually *not yet implemented* is a better description but this is something I forgot to deal with in the transition from `evaluate_smooth()` to `smooth_estimates()` and as such is a regression in behaviour. I'll fix the `dist` issue shortly.

Partial residuals aren't plotted when visualising 2D smooths, so `residuals = FALSE` shouldn't affect this at all. These points should be controllable via `rug` as they play the same role as the actual EDA-esque rug plots drawn on the axes of plots of 1D smooths.

**Comment by gavinsimpson** [comment]
This is now fixed:

```r
#with smooth_estimates()
sm_est <- smooth_estimates(b1, dist = 0.02)
ggplot(sm_est, aes(x = x, y = z, z = est, fill = est)) +
  geom_raster()
```
![issue-111-fig-1](https://user-images.githubusercontent.com/514696/130430725-f47fd340-0b48-4d10-a4bc-4a6d87b7e40e.png)

and

```r
draw(sm_est)
```
![issue-111-fig-2](https://user-images.githubusercontent.com/514696/130430789-c01d8ee2-507a-441c-90cf-dd2b2eda226a.png)

Thanks for letting me know about this.
