### ISSUE TITLE
Tweak draw() to allow theme specification

### ISSUE THREAD

**Issue by sponslerdb** [gavinsimpson/gratia#113]
From what I can tell, `draw()` uses the (fantastic) `patchwork` package to arrange multipanel figures. It would be nice to be able to tack on, say, `+ theme_light()` to the end of a call to `draw()` and have the chosen theme apply to all panels. At present, though, it only applies to the last panel in the series. Based on my experience with `patchwork`, I suspect that this is simply a matter of adding another set of parentheses to the internal `patchwork` call. 

`a | b + theme_light()` would apply the theme only to `b`.

But . . .

`(a | b) + theme_light()` should apply the theme to both `a` and `b`.   

This should be true of all similar calls to `ggplot2` functions that might be appended to a `patchwork` object.

**Comment by gavinsimpson** [comment]
@sponslerdb Thanks; I'll take a look. Internally I use `wrap_plots()` as the number of plots in not clear and I don't want to get into the business of writing code that writes R code.

One thing that I wondered about is:

```r
(draw(mod)) + theme_light()
```

but I haven't tried that yet.

**Comment by gavinsimpson** [comment]
Scratch that; the grouping and `+` operator combo doesn't work, but the `&` operator does:

```r
load_mgcv()
library('gratia')
library('ggplot2')
library('patchwork')

dat <- data_sim("eg1", n = 400, dist = "normal", scale = 2, seed = 42)
m1 <- gam(y ~ s(x0) + s(x1) + s(x2) + s(x3), data = dat, method = "REML")

draw(m1) & theme_light()
```

which produces

![Figure shows the result of a call to draw.gam with the addition of the light theme in ggplot created using the code above and the & operator to apply the theme to each individual plot in the display. The figure itself is a two by two display of estimated smooth functions with confidence intervals as estimated using the fitted model and simulated data from the code block above.](https://user-images.githubusercontent.com/514696/132496681-3f83487c-fdce-4ea6-8755-fe7e43d8c54c.png)

I will see about adding this as an example in `?draw.gam` or the vignettes I am producing for the package.

**Comment by sponslerdb** [comment]
Ah, that's an easy solution. Thanks!
