### ISSUE TITLE
Adding ggplot elements to draw elements

### ISSUE THREAD

**Issue by masger** [gavinsimpson/gratia#115]
The draw function returns a ggplot object, but somehow you cannot take your draw object and add other ggplot elements to it.

For example:

m1 <- gam(y ~ s(x0) + s(x1) + s(x2) + s(x3), data = dat, method = "REML") 

p1 = draw(m1) 

p1 + theme_bw()

Although it returns a ggplot element the true plot is not changed.

**Comment by gavinsimpson** [comment]
See #113

The plots are wrapped into an object with {patchwork} – I need to update the documentation to clarify this and show how to add elements like themes, but as shown in #113, you can do

```r
p1 & theme_bw()
```

to modify the theme for all plots.

**Comment by Aariq** [comment]
You can also pull out individual plots with [[]] and then modify them.
``` r
library(gratia)
library(ggplot2)
load_mgcv()

df1 <- data_sim("eg1", n = 400, dist = "normal", scale = 2, seed = 2)
m1 <- gam(y ~ s(x0) + s(x1) + s(x2) + s(x3), data = df1, method = "REML")

plots <- draw(m1)
plots
```

![](https://i.imgur.com/VkxGeiC.png)

``` r
plots[[1]] + theme_bw()
```

![](https://i.imgur.com/B57caEF.png)

``` r
plots[[1]] <- plots[[1]] + theme_bw()
plots
```

![](https://i.imgur.com/iaLSOnQ.png)

<sup>Created on 2021-09-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
