### ISSUE TITLE
Adding sizer to draw() in gratia

### ISSUE THREAD

**Issue by asanders11** [gavinsimpson/gratia#117]
Is it possible to add an argument similar to 'sizer' from your derivSimulCI() and CI fuctions to plot the first derivative of the spline, with sizer=TRUE to color increasing and decreasing parts of the spline?

Thanks!

**Comment by asanders11** [comment]
This is great, Gavin..thank you! And yes, I was hoping to plot significant periods of change as well.

**Comment by gavinsimpson** [comment]
I don't think I can implement this within `draw.gam()` itself as the way it works is quite complex already. I have implemented this in the `draw()` codes for `smooth_estimates()` objects however.

Now you can use `smooth_estimates()` to evaluate the smooths, then `add_sizer()` adds the derivative info needed, which the `draw()` method will recognise and plot:

```r
su_eg4 <- data_sim("eg4", n = 400,  dist = "normal", scale = 2, seed = 1)
su_m_factor_by <- gam(y ~ fac + s(x2, by = fac) + s(x0),
                      data = su_eg4, method = "REML")
smooth_estimates(su_m_factor_by) |>
  add_sizer(derivatives = d, type = "sizer")  |>
  draw(grouped_by = TRUE)
```

produces:

![plot-10](https://user-images.githubusercontent.com/514696/225279381-4d2e13da-9b5f-4fcb-8eb7-f0bad4adb8c8.png)

for example, showing that this works also with the new `groped_by` argument to group factor-by smooths.

So I'm going to call that closed for now. Hope that's OK? If I've missed something, let me know.

**Comment by asanders11** [comment]
Appreciate it, Gavin. This is exactly what I needed!

**Comment by asanders11** [comment]
Hi Gavin - sorry to bring you back to this topic, but do you know when `add_sizer()` will be added to _gratia_ ? Trying to use it with some data, but it doesn't seem to be in the new update (v 0.8.1). TIA!

**Comment by gavinsimpson** [comment]
It'll be a few weeks at least before I can get this on CRAN, but you don't need to wait for that; this is in the version on GitHub already, and the README.md file contains instructions on installing the package from the wonderful r-universe repo and build system.
