### ISSUE TITLE
Possibility to use "own" posterior simulation object in confint

### ISSUE THREAD

**Issue by raff-k** [gavinsimpson/gratia#120]
I would like to create simultaneous intervals based on a posterior simulation object created with `mgcv::gam.mh` ([RDocumentation](https://www.rdocumentation.org/packages/mgcv/versions/1.8-36/topics/gam.mh)) inside `gratia::confint`. Is there the possibility/plan to make the function more generic to allow a user such an input (e.g., a parameter `bs = my_simulation`)? - That would be great.

**Comment by gavinsimpson** [comment]
I plan on allowing this in general &mdash; see #86 &mdash; although I would have to think on the specific case of `confint()`. It won't be via users' own posterior simulation though, but an option to choose from Gaussian approximation, Metropolis Hasting (via `mgcv::gam.mh()`), and perhaps INLA (via `mgcv::ginla()`)

**Comment by gavinsimpson** [comment]
I'm going to close this here, but perhaps follow up in general in #86 ?

**Comment by gavinsimpson** [comment]
I see what you mean now and this is different from #86 . So let's reopen this and keep thinking about it. An option might be to allow to provide the posterior draws in a specific format/structure; for example using the {posterior} and {tidybayes} package ideas (the latter is something that I already have in mind for other areas of {gratia}. In which case I need a way to convert the output of `gam.mh()` into these formats also, which should be user visible.

**Comment by noamross** [comment]
Similarly, I would like to be able to use `gam.mh` outputs for gratia's `draw.*` methods, so as to plot all the model smooths (as well as confidence intervals) using the posterior simulation samples. I have some code I can contribute for converting `gam.mh` outputs (including multiple chains in a list from running in parallel) to common MCMC output formats like those used in `tidybayes` or `coda`.

**Comment by gavinsimpson** [comment]
This has been implemented. You can pass a matrix of posterior draws as argument `draws` to `posterior_samples()`, `fitted_samples()`, and `smooth_samples()` and set `method = "user"`.

Right now I am just keeping things simple and only allow a matrix of draws (1 column per coefficient, 1 row per draw).
