### ISSUE TITLE
Change `newdata` arg -> `data`

### ISSUE THREAD

**Issue by gavinsimpson** [gavinsimpson/gratia#140]
Quite a few functions have `data` and others `newdata` when accepting new values. This is inconsistent. Fix it.

* [x] `derivatives()`
* [x] `difference_smooths()`
* [x] `fitted_samples()`
* [x] `posterior_samples()`
* [x] `predicted_samples()`
* [x] `simulate()`
* [x] `smooth_samples()`
* [ ] `confint.gam()`

Have to be able to support `newdata` for a while. So look into whether {lifecycle} allows documenting deprecated *arguments*, and if user sets `newdata` to be anything that isn't `NULL`, trigger some warning/message and then move on, passing setting `data <- newdata`, or throwing an error if `data` *and* `newdata` are both set.

**Comment by scottkosty** [comment]
Thanks so much for your continued work on gratia, Gavin! And thanks for paying attention to the details (documentation, consistency, deprecation, detailed NEWS entries).

In the news item for the fix to this issue, I wonder if it would help to append something like "If you do adapt your code, it is not backwards compatible. Further, the backwards incompatibility might not result in an error in previous versions of Gratia so the user might not realize they are getting incorrect behavior. In particular, package authors relying on Gratia might consider requiring at least Gratia version 0.7.3.8".

My reasoning for the above suggestion is the following: if a user or package author writes their code using the new 'data' argument, and a different user on a previous version of Gratia runs that code, then I think they could get different results and no error. That is, if the argument 'data' is used in the current released version of Gratia, no error is given. I don't know whether it has an effect or if it is ignored (I'm not sure what the effect of `...` is in this case). This might cause some surprises, more so than if an error was given by previous Gratia versions.

Also one minor typo in NEWS: "takes it value" -> "takes its value".

**Comment by gavinsimpson** [comment]
Thanks @scottkosty I have added a warning as you suggest and fixed the typo.

**Comment by scottkosty** [comment]
@gavinsimpson Your explanation is very clear. Thanks for adding it!
