### ISSUE TITLE
aes_string and aes_ may be deprecated in the future are aren't recommended any longer

### ISSUE THREAD

**Issue by gavinsimpson** [gavinsimpson/gratia#159]
{gratia} makes extensive use of `aes_string()` and `aes_()` to build mappings for `ggplot()`. Seems like these may go away and are no longer recommended: https://ggplot2.tidyverse.org/articles/ggplot2-in-packages.html

So fix up all instances to a new idiom as indicated on that page

**Comment by hammadsheikh** [comment]
Hey Gavin. I am just starting to contribute to packages I like. If no one else is working on this issue, I would love to offer my help to fix up all instances of aes_string() and aes_(). Feel free to assign this issue to me.

**Comment by gavinsimpson** [comment]
Thanks for the offer @hammadsheikh! I'd already sat down and tackled most of this at the weekend

**Comment by hammadsheikh** [comment]
Really appreciate your project. Will have an eye out for other issues I can help you with in the future.
