### ISSUE TITLE
derivatives() should ignore random effect smooths

### ISSUE THREAD

**Issue by garincle** [gavinsimpson/gratia#168]
Hello, when using the derivative function I have got the following error:

```
Error in Summary.factor(c(1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 2L,  : 
  ‘min’ not meaningful for factors
```

please see:
https://stats.stackexchange.com/questions/573346/gam-statistically-comparing-fit-when-changing-covariates-in-gratia-r/574052#574052

for a detail description of the error, 
let me know if you need more information, 

Thank you again Gavin!

**Comment by gavinsimpson** [comment]
`derivatives()` doesn't know how to handle random effect smooths nor know to ignore them. Use the `term` argument to `derivatives()` to select the smooth you want derivatives for.

**Comment by garincle** [comment]
it works perfectly, thank you!
