### ISSUE TITLE
Function not applied to error bands for parametric terms in gamm

### ISSUE THREAD

**Issue by grasshoppermouse** [gavinsimpson/gratia#195]
![Screen Shot 2022-10-31 at 2 46 44 PM](https://user-images.githubusercontent.com/7534138/199116792-b8df91e4-5579-41c6-ad23-a16ad9348ad4.png)

**Comment by gavinsimpson** [comment]
Thanks for reporting this. I must have missed fixing this issue for parametric terms (it was fixed for smooths a version or two back 😭 )

FYI; `draw()` has a method for objects created by `gamm()` so you can just do `draw(m)` instead of `draw(m$gam)`.

**Comment by gavinsimpson** [comment]
This is now fixed in GitHub. Thanks again for letting me know about the problem
