### ISSUE TITLE
Size to linewidth

### ISSUE THREAD

**Issue by cmagelssen** [gavinsimpson/gratia#205]
![bilde](https://user-images.githubusercontent.com/51201964/215340618-0ba697b8-234d-44fe-a645-dd584790da63.png)

**Comment by gavinsimpson** [comment]
Hmm, thanks but I had actually caught all the ones in the code (I'd missed one in an example - now fixed).

Can you confirm what version of {gratia} you are using; the CRAN version will still have these issues but the GitHub version has all these fixed (see installation instructions to for how to get the dev version: https://github.com/gavinsimpson/gratia). You need to be running something higher than 0.7.3 and preferably the 0.8.0 version (which should have been on CRAN but, well, you saw my tweets about that on Friday). I should have 0.8.1 out just as soon as they get *dplyr* through CRAN's submission process.

If you still get these warnings with >=0.8.0 then it would be helpful to see what model/code lead to the warning.

**Comment by cmagelssen** [comment]
I had to double check this. It was because of the tutorial example and not the code per see. So I think this can be closed.
