### ISSUE TITLE
Change size to linewidth in the tutorial

### ISSUE THREAD

**Issue by cmagelssen** [gavinsimpson/gratia#207]
Nothing wrong with your package, but the tutorial uses size instead of linewidth. I just wanted you to know:
https://gavinsimpson.github.io/gratia/articles/gratia.html

**Comment by cmagelssen** [comment]
Sorry. I didn't saw the comments you had provided in the tutorial.

**Comment by gavinsimpson** [comment]
I should fix that though too!

**Comment by gavinsimpson** [comment]
Thanks; fixed now
