### ISSUE TITLE
partial residuals display default with draw

### ISSUE THREAD

**Issue by bachlaw** [gavinsimpson/gratia#228]
Gavin,

Thanks for the great package. 

Would it be possible for the `draw` function to either disable by default (or provide the option to disable) the display of partial residuals in splines of multiple dimensions? Right now, as the function notes, this option is ignored for splines of more than one dimension, but the challenge is that displaying a whole bunch of partial residuals, especially in larger datasets, tends to obscure much of the interesting information on the heat map. At some point, the partial residual dots tend to black out everything.

If it is more trouble than it is worth, I certainly understand, and I can always code up my custom layers per your vignette, but I thought this would be a more helpful default for most users.  

Thanks again.

**Comment by gavinsimpson** [comment]
Those aren't residuals; you want to turn off the rug plot with `rug = FALSE`.

**Comment by bachlaw** [comment]
> Those aren't residuals; you want to turn off the rug plot with `rug = FALSE`.

Right you are.  That fixed it.  Thanks a lot.
