### ISSUE TITLE
draw fails with ti(...) terms from smooth_estimates(...)

### ISSUE THREAD

**Issue by wStockhausen** [gavinsimpson/gratia#260]
The example from smooth_estimates(...) is:
```
load_mgcv()
# example data
df <- data_sim("eg1", seed = 21)
# fit GAM
m <- gam(y ~ s(x0) + s(x1) + s(x2) + s(x3), data = df, method = "REML")
# plot all of the estimated smooths
sm <- smooth_estimates(m)
draw(sm)
```
When s(x0) is replaced by  ti(X0), the example fails when draw'ing the sm object:
```
load_mgcv()
# example data
df <- data_sim("eg1", seed = 21)
# fit GAM
m <- gam(y ~ ti(x0) + s(x1) + s(x2) + s(x3), data = df, method = "REML")
# plot all of the estimated smooths
sm <- smooth_estimates(m)
draw(sm)
```
with error message: 
Error in `wrap_plots()`:
! Only know how to add <ggplot> and/or <grob> objects
Run `rlang::last_trace()` to see where the error occurred.

**Comment by gavinsimpson** [comment]
Thanks for the bug report, @wStockhausen. I wasn't anticipating univariate tensor products when I was building plot methods internally in the package. These univariate tensor products are now given their own unique type (to distinguish them in the outputs that these are univariate) but are plotted like standard mgcv smooths:

```
> smooth_estimates(m_univar_ti)
# A tibble: 100 × 6
   .smooth .type                  .by   .estimate   .se      x2
   <chr>   <chr>                  <chr>     <dbl> <dbl>   <dbl>
 1 ti(x2)  1d Tensor product int. NA       -4.58  0.614 0.00164
 2 ti(x2)  1d Tensor product int. NA       -4.11  0.575 0.0117 
 3 ti(x2)  1d Tensor product int. NA       -3.65  0.536 0.0218 
 4 ti(x2)  1d Tensor product int. NA       -3.18  0.499 0.0318 
 5 ti(x2)  1d Tensor product int. NA       -2.72  0.463 0.0419 
 6 ti(x2)  1d Tensor product int. NA       -2.26  0.429 0.0520 
 7 ti(x2)  1d Tensor product int. NA       -1.81  0.397 0.0621 
 8 ti(x2)  1d Tensor product int. NA       -1.37  0.368 0.0721 
 9 ti(x2)  1d Tensor product int. NA       -0.934 0.341 0.0822 
10 ti(x2)  1d Tensor product int. NA       -0.508 0.318 0.0923 
# ℹ 90 more rows
# ℹ Use `print(n = ...)` to see more rows
```

This change is live now in the GitHub development version of gratia so you can install from there with

```r
remotes::install_github("gavinsimpson/gratia")
```
if you are able to build from source. If not, I'd expect my r-universe to have a binary build ready in the next few hours and to install from there use

```r
install.packages("gratia", repos = c(
  "https://gavinsimpson.r-universe.dev",
  "https://cloud.r-project.org"
))
```

And a version that fixes this should be on CRAN before the end of the month if all goes well.

**Comment by wStockhausen** [comment]
Wow! Thanks for the instant response. BTW, love the package.

*William T. Stockhausen*

Research Fishery Biologist, Alaska Fisheries Science Center

NOAA Fisheries | U.S. Department of Commerce

Office: (206) 526-4241

www.fisheries.noaa.gov
