### ISSUE TITLE
prediction-based plots when using by matrices in linear functionals 

### ISSUE THREAD

**Issue by nicholasjclark** [gavinsimpson/gratia#261]
Hi Gavin,
I noticed a *potentially* unwanted feature when setting up some linear functionals with `by` matrices. The prediction function in `gratia` is (understandably) taking some sort of average value for the weights when making conditional smooth plots, but this can lead to failures. The example below illustrates. Not sure what could be done to remedy this, or in fact whether there is already a solution that I'm not aware of in `gratia`, but perhaps there could be options allowing users to supply certain data objects rather than averaging over them? In this simple case, simply setting all the weights = `1` should be enough I'd think

``` r
library(mgcv)
#> Loading required package: nlme
#> This is mgcv 1.8-42. For overview type 'help("mgcv-package")'.
library(gratia)
#> Warning: package 'gratia' was built under R version 4.3.2
packageVersion('gratia')
#> [1] '0.8.2'

# Simulate a covariate
set.seed(123)
x <- rnorm(200)

# Lagged covariate matrix
lagard <- function(x, n_lag = 6) {
  n <- length(x)
  X <- matrix(NA, n, n_lag)
  for (i in 1:n_lag){
    X[i:n, i] <- x[i:n - i + 1]
  } 
  X
}

x_lag <- lagard(x, n_lag = 6)
x_lag <- x_lag[complete.cases(x_lag),]

# Factor levels
fac <- as.factor(c(rep('fac1', NROW(x_lag) / 3),
                   rep('fac2', NROW(x_lag) / 3),
                   rep('fac3', NROW(x_lag) / 3)))

# Lag matrix
lag <- matrix(0:5, nrow(x_lag), 6, byrow = TRUE)
stopifnot(all.equal(dim(x_lag), dim(lag)))

# Weights matrices for the factor levels
weights_f1 <- weights_f2 <- weights_f3 <- 
  matrix(1, nrow = NROW(lag), ncol = NCOL(lag))
weights_f1[!(fac == levels(fac)[1]), ] <- 0
weights_f2[!(fac == levels(fac)[2]), ] <- 0
weights_f3[!(fac == levels(fac)[3]), ] <- 0

# Outcome
y <- rnorm(NROW(lag))

# Data list
dat <- list(y = y,
            fac = fac,
            x_lag = x_lag,
            lag = lag,
            weights_f1 = weights_f1,
            weights_f2 = weights_f2,
            weights_f3 = weights_f3)
          
# Set up group-varying distributed lags using weights as 
# the 'by' arguments
mod <- gam(y ~ 
             te(x_lag, lag, k = 4, by = weights_f1) +
             te(x_lag, lag, k = 4, by = weights_f2) +
             te(x_lag, lag, k = 4, by = weights_f3),
           data = dat)

# mgcv plotting works as it seems to keep the by matrices fixed in prediction
plot(mod, pages = 1, scheme = 2)
```

![](https://i.imgur.com/s9umpgh.png)

``` r

# gratia does not; seems to be setting all the weights
# to zero when setting up the predictions
draw(mod)
#> Warning: `stat_contour()`: Zero contours were generated
#> Warning in min(x): no non-missing arguments to min; returning Inf
#> Warning in max(x): no non-missing arguments to max; returning -Inf
#> Warning: `stat_contour()`: Zero contours were generated
#> Warning in min(x): no non-missing arguments to min; returning Inf
#> Warning in max(x): no non-missing arguments to max; returning -Inf
#> Warning: `stat_contour()`: Zero contours were generated
#> Warning in min(x): no non-missing arguments to min; returning Inf
#> Warning in max(x): no non-missing arguments to max; returning -Inf
```

![](https://i.imgur.com/XnuKrUZ.png)

<sup>Created on 2024-03-14 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by gavinsimpson** [comment]
Thanks for the heads-up @nicholasjclark; the handling of mgcv's linear functional capabilities is pretty limited in {gratia} just now. Some of the model forms allowed by mgcv are supported (not that this is documented anywhere though); DLNM type formulations work, but I don't think I've tried any of the models with matrix `by` terms.

@dill has mentioned that he and a colleague have been thinking about better displays for linear functional terms.

Once I get v0.9.0 shipped to CRAN I can take a closer look at these things. But I'll look at this specific example before hand to see if it's an easy fix.

**Comment by gavinsimpson** [comment]
I spoke too soon; seems this has already been fixed in the GH version. With

```r
draw(mod)
```

I now see

![gratia-issue-261](https://github.com/gavinsimpson/gratia/assets/514696/87779d8e-ca09-473e-a8dd-858e53d9a4bb)

which seems to correspond to what `mgcv:::plot.gam()` produced.
