### ISSUE TITLE
Select mvn_method when running `fitted_samples()`

### ISSUE THREAD

**Issue by stefgehrig** [gavinsimpson/gratia#279]
While `post_draws()` contains the possibility to set `mvn_mehod` (the package/method to simulate form the multivariate normal implied by the fitted vcov matrix), this option is not available in `fitted_samples.gam()`, which calls `post_draws()`.

Is there a reson for this? It would be handy to switch to `mvn_method = "mgcv"` from the default `mvn_method = "mvnfast"` when using `method = "gaussian"` with `fitted_samples.gam()`. In my case, the cholesky decomposition used by mvnfast failed, so I needed to switch to the (slower) implementation.

A very easy fix would be to add the default `mvn_method = "mvnfast"` explicitly to the signature of `fitted_samples.gam()`, and the signature `mvn_method = mvn_method` to the call to `post_draws()` within `fitted_samples.gam`.

**Comment by gavinsimpson** [comment]
Quite right: weirdly, one of the other methods for models fitted by `scam()` did allow this and I think I must have gotten distracted after adding it to that method and never got round to adding to all the other methods as well.

I'm just checking some fixes for this, which should be on GitHub soon.
