### ISSUE TITLE
How to draw() the result of get_by_smooth?

### ISSUE THREAD

**Issue by lhare** [gavinsimpson/gratia#29]
Thanks for this great package!  This is probably a better question for the blog post about gratia but I wasn't able to make it past the captcha.

I'm trying to 'draw' the result of a 'get_by_smooth" and getting

Error in xy.coords(x, y, xlabel, ylabel, log) : 
'x' is a list, but does not have components 'x' and 'y'

I want to plot the smooth on the x axis and the response on the y axis, and can't find a way to do something like this in the help.

**Comment by gavinsimpson** [comment]
I wouldn't use `get_by_smooth()` for this &mdash; it is exported only as a helper for developers wanting to identify and extract a by variable smoother.

Use `evaluate_smooth()` or `draw()` on the fitted model and select the smooth you want. However, in trying `draw()` I am seeing a bug which I'll have to fix.

For example:

```r
library('gratia')
library('mgcv')
set.seed(42)
dat <- gamSim(4, n = 400, verbose = FALSE)
m <- gam(y ~ fac + s(x2, by = fac) + s(x0), data = dat)
draw(m, select = 's(x2)')
```

The latter is supposed to work, but it isn't and I'll raise an issue to get this fixed.

Following on from the above example you could use `evaluate_smooth()` to get back the data the `draw()` is extracting internally and then draw the plots yourself:

```r
es <- evaluate_smooth(m, smooth = 's(x2)')
es

library('dplyr')
## add 95% credible interval
es <- mutate(es, lower = est - (2 * se), upper = est + (2 * se))

## plot
library('ggplot2')
ggplot(es, aes(x = x2, y = est)) +
  geom_ribbon(aes(ymax = upper, ymin = lower, x = x2), inherit.aes = FALSE,
              alpha = 0.2) +
  geom_line() +
  facet_wrap(~ smooth)
```

Which produces

![gratia-draw-by-smooth-manually](https://user-images.githubusercontent.com/514696/52870895-81e3bd80-310e-11e9-85da-66babb415cf2.png)

And then you can modify from there. Or do as `draw()` does and prepare separate plots for each smooth, but filtering the `es` object on the `smooth` column to select each of the smooths in turn and prepare a plot as above for each smooth separately and then use `cowplot::plot_grid()` to arrange them on the plot device.

**Comment by lhare** [comment]
Hi Gavin,

Many, many thanks for your detailed help with this! And for this cool packager publishable GAM plots.
Liz
