### ISSUE TITLE
`derivative_samples` scale argument 

### ISSUE THREAD

**Issue by jonathonmellor** [gavinsimpson/gratia#293]
Hi Gavin,

Am re-exploring some work I have done on growth rates and was thinking if there was a better way I could use the package. I was thinking of using the `derivative_samples` linear predictor to get the derivative of smoothed count data on a log scale.

Looking into the code, it looks like the `scale` argument may currently be unused? 

Within R/posterior-samples.R it describes the fits generated:

```
  ## compute posterior draws of E(y) (on response scale)
  fs <- fitted_samples(
    model = object, n = n_sim, data = fd_data,
    method = method, seed = seed, draws = draws,
    mvn_method = mvn_method, ...
  )
```

The follow on computation of derivative doesn't appear to convert back to the scale set.

Could this perhaps propagate the choice of `scale` within the function, to produce the linear predictor derivative.

As always, thank you for the fantastic work on the package!

**Comment by jonathonmellor** [comment]
Good chance I have gotten something a bit wrong in my analysis, but changing the scale argument appears to give me the same results.. so am a bit wary!

**Comment by gavinsimpson** [comment]
Yeah, that looks like an oversight; I obviously planned to allow this but I wrote this for someone who wanted response derivatives for some joint work, and I never circled back to generalize it a bit.

I'll fix this shortly.

**Comment by jonathonmellor** [comment]
Thanks very much!

**Comment by jonathonmellor** [comment]
Awesome, have tested the GitHub version it on my end and all working as expected
