### ISSUE TITLE
Rug plots

### ISSUE THREAD

**Issue by nadyacaro** [gavinsimpson/gratia#33]
There is any command in the function draw, that allow to include the observations in the margins (rug plot). I have tried the ggplot function geom_rug() but it does not work.
Thank you

**Comment by gavinsimpson** [comment]
Not yet, but it is on my ToDo list (I'll change the Issue title here and have this issue act as the tracker for me to add it).

If you really need this sooner, use `evaluate_smooth()` on selected smooths, one at a time, and then plot the data from the tibble that it returns or use the `draw()` method on the single evaluated smooth.

```r
library('mgcv')
library('ggplot2')
library('gratia')

dat <- gamSim(1, n = 400, dist = "normal", scale = 2)
m1 <- gam(y ~ s(x0) + s(x1) + s(x2) + s(x3), data = dat, method = "REML")

## evaluate the estimated smooth
sm <- evaluate_smooth(m1, smooth = "s(x1)")
## plot the smooth and add the rug plot
draw(sm) + geom_rug(sides = "b")
```

![rug-plot](https://user-images.githubusercontent.com/514696/53360545-6b521900-38fb-11e9-85c5-e1bf2aea9014.png)

**Comment by nadyacaro** [comment]
Thank you, it works perfectly one smooth at the time.

**Comment by nadyacaro** [comment]
I will add that if you want to make the rug plot, 
#plotting the variable values as the function plot(m1) then:
draw(sm) + geom_rug(sides = "b", data=dat, aes(x=dat$x0),inherit.aes = F)
![image](https://user-images.githubusercontent.com/2878203/53410656-48d40480-39bc-11e9-9b96-a90250125abc.png)

**Comment by gavinsimpson** [comment]
:man_facepalming: of course you need to plot the data not the points we evaluated the smooth at. I blame the fever I picked up while travelling last week...

**Comment by gavinsimpson** [comment]
Found a hour today to implement this. `draw()` will by default plot rugs for GAM models. For individual smooths, you need to pass the data currently for the rug, which is what the `draw.gam` method arranges to happen.

**Comment by nadyacaro** [comment]
Thank you!!  I will try it after updating the package.

**Comment by nadyacaro** [comment]
draw.gam() have not worked for me yet

I did manage to create my smooth plots using
## evaluate the estimated smooth
sm <- evaluate_smooth(m1, smooth = "s(x1)")
## plot the smooth and add the rug plot
sm<-draw(sm) + geom_rug(sides = "b", data=dat, aes(x=dat$x0),inherit.aes = F)
## grid
plot_grid(sm, ..)

But, one of my covariates is a factor and not a smooth, I am not able to use 'evaluate_smooth' 
which function do you use to extract the factor terms in a gam?
Using the function draw () factors are automatically ploted, but I would like to have the rug plots for my smooth covariates plus my factor plot.
Many thanks

**Comment by gavinsimpson** [comment]
@nadyacaro Did you reinstall from github using `devtools::install_github('gavinsimpson/gratia')`? If you did, was something not working/failing with `draw.gam()`? It is working for me locally and on travis for the released version but I'm seeing some errors only on travis under r-devel, which I'm not able to reproduce locally.

For the parametric terms, use `evaluate_parametric_terms()`, which may not be exported so you may need to preface it with `gratia:::`

But I'm interested in knowing what / if anything isn't working with `draw.gam()` for you.

**Comment by nadyacaro** [comment]
I have updated and just re-do it just for checking, still getting the same problem

![image](https://user-images.githubusercontent.com/2878203/53579214-14ee1000-3b71-11e9-83b9-b2288886ac10.png)

regarding the factor covariate:
![image](https://user-images.githubusercontent.com/2878203/53579588-b8d7bb80-3b71-11e9-9fd6-6b277c2ed715.png)

**Comment by gavinsimpson** [comment]
Sorry for the confusion here. `draw()` is a (S3) generic function, which has several methods specified for it. When you do `draw(model)`, R looks at the type of object `model` is, its class(es), and then looks for a method for that class. If it finds one, it calls that method and if not if looks for any of the classes that `model` inherits from, and if no suitable methods are found it throws an error. When `model` is a `gam` object, R will end up calling the *method* `draw.gam()`. As a user you should not need to know that it is `draw.gam()` and hence convention is that these methods are not exported from package namespaces. This explains the first error as `draw.gam()` is not a function known to your R session, it is only known inside the *gratia* namespace and through the S3 method registration process.

If you were to use `draw(gam3.F2.2)` you'd get the desired result.

As for the second error, you need *three* colons; `gratia:::evaluate_parametric_terms()` because this function is not exported. The double colon operator `::` is the way to reference *exported* functions. Anyway, you shouldn't need this if you just use `draw(gam3.F2.2)`.

**Comment by nadyacaro** [comment]
Thank you for the explanation.
Running the example from before:
draw(m1)
![image](https://user-images.githubusercontent.com/2878203/53581407-68faf380-3b75-11e9-8d8d-5e88c210873b.png)

Running with the preface `gratia:::`
![image](https://user-images.githubusercontent.com/2878203/53581581-c000c880-3b75-11e9-98b4-c296a450e5c2.png)

**Comment by gavinsimpson** [comment]
Can you post the output from `sessionInfo()` with *gratia* loaded?

And that second one is my mistake; you want `evaluate_parametric_term()` (not `terms`). You don't need the `gratia:::` either as I just checked an I have exported this. You will need

```r
evaluate_parametric_term(gam3.F2.3, term = "foo")
```

replacing `"foo"` with the parametric term you want.

**Comment by gavinsimpson** [comment]
With the latest github version installed, I see

![gam-rug-plots](https://user-images.githubusercontent.com/514696/53582394-00941e00-3b45-11e9-9c1a-7ba0683eb577.png)

with `draw(m1)` from the original example.

You might need to restart R and reload packages if you aren't seeing this. Note I haven't updated the CRAN version yet as I'm still dealing with a few other issues, so you need to be able to install from github with:

```r
install.packages('devtools')
devtools::install_github('gavinsimpson/gratia')
library('gratia')
```

in a clean session. If any of those lines give an error then can you show me that error and the output from `sessionInfo()`?

**Comment by nadyacaro** [comment]
Thanks, I re-installed and is working now!!

Also the factor just need to put: as.factor(variable)
evaluate_parametric_term(gam3.F2.3, term = "as.factor(foo)")
only 'foo' was not recognizing the term

**Comment by gavinsimpson** [comment]
@nadyacaro Glad the `draw()` method is working now.

I presume you use `as.factor(foo)` in the formula when you fit your GAM? If you did, I'd advise you to not do this and to prepare your data by converting to a factor or creating a new variable that is a factor version of the original before using it to fit the GAM. Or any model for that matter. As you have found, R views the term to have the name `as.factor(foo)` not `foo`, so if you want to predict etc, you need to create a variable with the name `as.factor(foo)`, which isn't quite so easy to do.

**Comment by nadyacaro** [comment]
Good point, thank you for the advice.
