### ISSUE TITLE
confint() for derivatives() objects in addition to fderiv() objects?

### ISSUE THREAD

**Issue by slarge** [gavinsimpson/gratia#38]
@gavinsimpson [replied on twitter](https://twitter.com/ucfagls/status/1054825179866718209
): "The pointwise intervals can be added easily; I'm thinking add_confint() as the function to add them. I need to think about how to do the simultaneous intervals; they need something not easily passed in a tibble so I need a little more work to figure it out."

Do you think this still on the table? Thanks again for a fantastic package. Very useful.

**Comment by gavinsimpson** [comment]
I think this is already implemented for `derivatives()`; I didn't do it via `add_confint()` as then I don't think I could make the simultaneous intervals work, at least not without drastically modifying the ways objects are returned, so I just added the intervals as pert of the computations for `derivatives()`.

See the [derivatives documentation](https://gavinsimpson.github.io/gratia/reference/derivatives.html) for an example.

If something is missing, let me know and we can discuss it.

**Comment by gavinsimpson** [comment]
To make this work via `add_confint()` or similar, I'd need to make the returned objects have list columns and the returned object would have to be a tibble with 1 row per smooth, the elements of that tibble would then be tibbles or list columns containing the current output from `derivatives()` plus a list containing the lpmatrix things we need for simultaneous intervals.

**Comment by slarge** [comment]
Wow, this is fantastic. Thanks for your speedy reply! I think this is exactly what I'm after. I didn't notice the updated documentation, so thanks for pointing me in the right direction.

**Comment by gavinsimpson** [comment]
No worries and glad this answers your question/feature request.
