### ISSUE TITLE
draw.derivatives is documented, but not part of CRAN package

### ISSUE THREAD

**Issue by sedot42** [gavinsimpson/gratia#41]
draw.derivatives is part of the documentation at https://cran.r-project.org/web/packages/gratia/gratia.pdf, but not part of the distributed package.
How to reproduce:
```R
> install.packages("gratia")
> gratia::draw.derivatives
Error: 'draw.derivatives' is not an exported object from 'namespace:gratia'
```

**Comment by gavinsimpson** [comment]
You can't access **unexported** functions using the `::` operator. *gratia* is working as expected:

```r
r$> head(gratia:::draw.derivatives)
                                                                        
1 function (object, select = NULL, scales = c("free", "fixed"),         
2     alpha = 0.2, align = "hv", axis = "lrtb", ...)                    
3 {                                                                     
4     scales <- match.arg(scales)                                       
5     sm <- unique(object[["smooth"]])                                  
6     select <- check_user_select_smooths(smooths = sm, select = select)
```

The function `draw.derivatives` is a (S3) method for the `draw()` generic function, for objects of class `"derivatives"`. These are intentionally not exported from packages any longer. Instead the S3 methods are registered with the R session when the package is loaded. When you call `draw()` on an object `obj`

    draw(obj)

R does method dispatch and identifies a method for the class of object the `obj` is. In this case, the `draw.derivatives()` function is dispatched too and this function is visible to method dispatch code.

As I showed above, you need to use `:::` to access unexported objects from a package's namespace. Alternatively, use `getAnywhere()` to look for functions
```r
getAnywhere(draw.derivatives)
```

```
r$> getAnywhere(draw.derivatives)
A single object matching ‘draw.derivatives’ was found
It was found in the following places
  registered S3 method for draw from namespace gratia
  namespace:gratia
with value
....
```

**Comment by sedot42** [comment]
Thank you that you took the time to write such an elaborate answer. I learned something. Much appreciated!
