### ISSUE TITLE
Clarify type of finite difference in fderiv()

### ISSUE THREAD

**Issue by mikeguggis** [gavinsimpson/gratia#59]
It appears that the finite difference used in fderiv() is a "forward" derivative. It would be helpful if the documentation clarified that.

**Comment by gavinsimpson** [comment]
I should deprecate `fderiv()` as *gratia* now has `derivatives()` which does forward, backward, and, central finite differences, but I keep it around because of old blog posts etc. I can put a note in `?fderiv` to direct people toward `derivatives()` though
