### ISSUE TITLE
Add "forward", "backward", or "central" derivative options to fderiv()

### ISSUE THREAD

**Issue by mikeguggis** [gavinsimpson/gratia#60]
In many applications I am interested in a 1 unit change (increase or decrease). It appears that fderiv() uses a forward derivative, thus I can obtain a 1 unit change with eps=1. However, a 1 unit decrease would require me to subtract 1 from the smoothed variable and pass it through newdata. It would be easier if there was a  "forward", "backward", or "central" derivative options to fderiv(). Alternatively, the numerical derivative could be calculated with numDeriv:grad() and utilize the arguments of said function.

**Comment by gavinsimpson** [comment]
Forward, backward, and central finite derivatives are already implemented in [`derivatives()`](https://gavinsimpson.github.io/gratia/reference/derivatives.html)
