### ISSUE TITLE
Add documentation about output via @return

### ISSUE THREAD

**Issue by damianooldoni** [gavinsimpson/gratia#63]
It would be useful to add section @return to documentation of `derivatives()`. In this way the users could better understand the output. It would be nice to explain all columns of the returned data.frame. For example, what `crit` stands for? 
I see also you already did it for other functions.
What do you think? Thanks in advance and congrats for this nice package!

**Comment by gavinsimpson** [comment]
I guess I forgot about that as I wasn't 100% set on the exact structure of the returned object (which goes for the rest of the pkg just now; it's quite early in the development cycle).

`crit` is the critical value required such that `derivative + (se * crit)` and `derivative - (se * crit)` form the upper and lower bounds of the `level` * 100%  simultaneous or confidence interval on the derivative of the estimated smooth (where `level` is an argument to `derivatives()`. There's not much point in having this in the object but for simultaneous intervals it can be useful to know how much wider the intervals are over the same normal/confidence interval.

**Comment by gavinsimpson** [comment]
I've documented this now: https://gavinsimpson.github.io/gratia/reference/derivatives.html
