### ISSUE TITLE
Axes not fixed if 3-D smooths are present

### ISSUE THREAD

**Issue by StefanoMezzini** [gavinsimpson/gratia#73]
`draw` does not allow `scales = 'fixed'` if `ti()` terms are plotted. It would be nice to be able to have a common axis for 2-D smooths (i.e. `s()`) and the z axis of `ti()` terms (i.e. the color scale).

```
plot_grid(draw(m, scales = 'fixed'),
          draw(m, scales = 'fixed', select = 1:3))
```
![image](https://user-images.githubusercontent.com/42444204/82576654-2b520400-9b47-11ea-8036-99a77c9e3281.png)

**Comment by gavinsimpson** [comment]
Thanks @StefanoMezzini I have fixed the bug (the 1-d smooths should have been fixed but not the 2-d one). I have also adapted the code so that all plots will have a fixed scale now if requested.

**Comment by gavinsimpson** [comment]
These changes will be in version 0.4.1 which I am packaging up for CRAN at the moment. So hopefully there in the next few days.

**Comment by User1122334** [comment]
Dear Gavin, 
I still or again get the same problem today with gratia version 0.8.1. 
In fact, if I add `scales = "fixed"` to the draw function only the 2D smoothers change their color scales (which are also not consistent afterwards) but all the 1D smoothers keep their Y axis scaled in different intervals.

Thanks for your work!

**Comment by gavinsimpson** [comment]
@User1122334 I'll need a reproducible example, because this is working for me:

```r
library("gratia")
library("mgcv")
su_eg1 <- data_sim("eg1", n = 1000, dist = "normal", scale = 2, seed = 1)
draw(m, scales = "fixed", rug = FALSE)
```

which produces

![gratia-issue-73](https://github.com/gavinsimpson/gratia/assets/514696/882202b0-1e90-478f-a19a-4fe63d4d8e9e)
