### ISSUE TITLE
excluding random effects when using simulate.gam

### ISSUE THREAD

**Issue by hgoldspiel** [gavinsimpson/gratia#74]
Is it possible to ignore random effects when using `simulate.gam()` with new data? It seems there is only a `newdata` argument in the function, and no way to include an `exclude` or `newdata.guaranteed` argument as I normally would in `predict.gam()` when I want to average responses over random effects. Thanks!

**Comment by gavinsimpson** [comment]
Thanks for the suggestion; no `simulate.gam()` doesn't allow this but it would be trivial to add by passing the additional argument to `predict.gam()`. I'll add this shortly.

**Comment by gavinsimpson** [comment]
You can now pass `exclude`, `terms` etc to `predict.gam()`

**Comment by hgoldspiel** [comment]
Thanks! Excited to use this!
