### ISSUE TITLE
When plotting 2d (or higher) thin-plate splines should `draw()` default to equal axis scaling?

### ISSUE THREAD

**Issue by gavinsimpson** [gavinsimpson/gratia#81]

**Comment by dill** [comment]
Can I lodge a quick vote for "yes" here. The isotropy assumption inherent in tprs means that not setting the axis aspect ratio to 1 is misleading, imo. Obvs. this is only the case where the dimension of an individual tprs component is >=2 and shouldn't count for things like `te(x,y,bs="tp",d=c(1,1))`.

**Comment by gavinsimpson** [comment]
Thanks @dill, I'd forgotten about this (or rather thought it was related to having a common scale for displaying the effect of the smoother across all panels; I really should add descriptions when I add issues 😠).

This is relatively trivial to fix so I'll get it done and ticked off the list.

**Comment by Lachlan00** [comment]
Is there an argument to turn the new default off for when X and Y have different units? Can make it very hard to read what's going on. For example when plotting temperature (degrees) vs salinity (PSU) the range for the units is very different so you can end up with really disproportionate aspect ratio.

You can force it using `coord_cartesian()` in most cases except this doesn't work if you include a 'by' term in the smooth becuase `draw` returns a patchwork object.  

```
library(mgcv)
library(gratia)

x <- 1:400
y <- x*3 + runif(100, -40, 40)
df <- data.frame(x=x, y=y, z=y*sin(x), g=factor(rep(c('A','B','C','D'), each=length(x)/4)))

fit <- gam(z ~ s(x, y), data=df)
draw(fit, residuals=T) + coord_cartesian()

fit <- gam(z ~ s(x, y, by=g), data=df)
draw(fit, residuals=T) + coord_cartesian()
```

**Comment by gavinsimpson** [comment]
The last line should be:

```
draw(fit, residuals=T) & coord_cartesian()
```

using the `&` operator because the object is, as you say, a patchwork.

And no, there isn't an argument for not treating the smooth as isotropic; I can see why it might be beneficial in some cases because of the way patchwork works with `coord_fixed()` (or `coord_equal()`) but I think as a general purpose default plotting tool it would be better (and simpler in the code) to just do the right thing for isotropic multidimensional thin plate splines.

You can control everything you want by doing the plotting by hand; just use `sm <- smooth_estimates(fit)` to return all the data needed to plot the estimated smooths and then you can filter `sm` and plot each smooth exactly how you want to. The vignette here https://gavinsimpson.github.io/gratia/articles/custom-plotting.html shows how to do this and the `&` operator in more detail.

I'm a good argument can be made to justify having the original behaviour as a user-selectable choice via an argument I can look into how much work it is to handle it.

**Comment by dill** [comment]
Not to be too much of a nerd killjoy here but... if you have covariates on different scales then the inbuilt assumption of thin plate regression splines is probably doing something wrong as you probably don't think that the smoothness of the 2 (or more) covariates is the same (i.e., those covariates (probably) vary at different rates). So, I think having tprs use `coord_equal()` is correct and highlights when things might go wrong. In the case where you have different scales for each variable, it's probably better to use `te()`.

(Sorry for using the word "probably" so many times in one paragraph.)

**Comment by gavinsimpson** [comment]
Argh, sorry I completely missed the bit of your post @Lachlan00 where you said you have different units. I 100% agree with @dill on this; those *should* be modelled using tensor products. When I skipped over your text about units I then misunderstood the `x` and `y` covariates as being space and thought you were talking about a spatial problem where the distance in say `x` is of lesser range than `y` (think Portugal) which then doesn't fill the space so nicely now that we force equal scaling of axes. My only excuse for the brain fart is that I was travelling for 20 hours yesterday and my body is still on Eastern time despite being back in Europe.

Thinking on this more, not allowing one to have unequal axis scaling is a useful pain-point for users as it's more likely to highlight misuses of the thin plate spline if those smooths always plot with equal scaling.

**Comment by Lachlan00** [comment]
Ah thanks for that Gavin! I didn't know about the `&` operator for patchwork.

In my field (marine ecology) we often use variables with very different units (for example water temperature might range from 12-20 degrees while salinity might range 34.40 to 34.65 PSU). But quite honestly, it is very simple to just add `coord_cartesian()` and now that you mentioned the '&' operator for patchwork objects I'm less convinced about the need for a dedicated argument.

Also thanks for maintaining this library! I just discovered gratia recently and it's ben saving me a ton of time and effort! Much appreciated!
