### ISSUE TITLE
Compare smooths across models

### ISSUE THREAD

**Issue by gavinsimpson** [gavinsimpson/gratia#85]
@dill asked about comparing smooths across models and plotting them. Dave's example was comparing smooths (covariate-wise) across models with different types of null space penalties (none, shrinkage smooths, double penalty), and provided a [gist](https://gist.github.com/dill/61599d96628b7b82e9dfc61cda3195c1) to show some intended output.

I'm thinking of implementing:

* [ ] `compare_smooths(...)` which can take two or more models via argument `...` (and or a list of models for flexibility), plus the name (or names) of smooths to compare. Should return an object like that returned by `evaluate_smooth()` but with an extra column identifying the model from which each thing was drawn.
    * [ ] Will need to handle `by` smooths as well.
    * [ ] Needs a `draw()` method
* [ ] `add_layer(obj)` methods so you could do some of the above by hand. `add_layer()` would simply try to add `geom_line()` and optionally `geom_ribbon()` layers to an existing ggplot object but where the data has been replaced by a new data object, which is the result of a call to `evaluate_smooth()` on `obj`.

**Comment by dill** [comment]
This sounds great and pretty much what I had in mind. Feel free to ping on me to test 👍
