### ISSUE TITLE
Option to rotate axis label

### ISSUE THREAD

**Issue by tamas-ferenci** [gavinsimpson/gratia#87]
It'd be useful to add an option to `gam::draw` which allows the rotation of the axis labels (should the user have a factor covariate with relatively long names).

**Comment by gavinsimpson** [comment]
Do you mean for the plot of parametric terms? If so that could probably be arranged.

**Comment by tamas-ferenci** [comment]
Yes, I meant the parametric part, sorry for not being clear.

**Comment by gavinsimpson** [comment]
Sorry for the long wait on this one @tamas-ferenci, but it is now implemented in the version in GitHub (not for the old `evaluate_<foo>()` functions, but their more modern replacements plus most other `draw()` methods.)

**Comment by tamas-ferenci** [comment]
Thank you very much!
