### ISSUE TITLE
confint not working for te smooths

### ISSUE THREAD

**Issue by tamas-ferenci** [gavinsimpson/gratia#88]
I thought that the following is a valid call to `confint`, but it doesn't seem to like it:

```
dat <- gamSim(1, n = 500, dist = "normal", scale = 2)
mod <- gam(y ~ te(x0, x1), data = dat, method = "REML")
confint(mod, parm = c("x1", "x2"), type = "confidence")
```

**Comment by gavinsimpson** [comment]
This seems to be an area where inconsistency has crept in; the original blog posts where I showed some of this stuff had `parm` be the name of a covariate, which didn't even make sense then properly but this clearly fails badly here. In newer functions I have used the default label that mgcv uses as a means for the user to identify smooth terms so I should do that for `confint()` too.

**Comment by gavinsimpson** [comment]
Thanks for this @tamas-ferenci. This shouldn't have worked anyway, as I was restricting confidence intervals to 1d smooth only elsewhere in the code, but I removed that restriction also.
