### ISSUE TITLE
Combine plots of `by = fac` smoothers

### ISSUE THREAD

**Issue by RPanczak** [gavinsimpson/gratia#89]
When using a smoother separated by a factor variable currently `gratia` plots separate panels for it 

```
library(gratia)
load_mgcv()
set.seed(42)
df <- gamSim(4, n = 400, verbose = FALSE)
m<- gam(y ~ s(x2, by = fac), data = df)
draw(m)
```

![ex](https://user-images.githubusercontent.com/31648642/95192756-ef0c0100-07d2-11eb-8b10-8b52fa9f3924.png)

Is it possible, or would it be desireable to have feature to plot these three smoothers on one plot using different color/line type for better comparisons?

**Comment by gavinsimpson** [comment]
It is desirable and possible.

I've been doing some work under the hood to make it easier to accommodate more models and smooth types, and now that most of that work is complete I will be porting `draw()` etc to those functions. Once that's done I'll see about offering this as an option.

**Comment by RPanczak** [comment]
Thank you for chasing that Gavin! =)

**Comment by gavinsimpson** [comment]
This is now possible with `draw.gam()` in the GitHub version of {gratia} (I'll work on `draw.smooth_estimates()` later) via new `argument `grouped_by`:

```r
df <- data_sim("eg4", n = 400,  dist = "normal", scale = 2, seed = 1)
m <- gam(y ~ fac + s(x2, by = fac) + s(x0),
                      data = df, method = "REML")
draw(m, grouped_by = TRUE)
```

which produces

![plot-9](https://user-images.githubusercontent.com/514696/225166797-8c6494b7-c395-40ab-91e6-2b8f6c95b574.png)

Sorry this took a bit longer than I expected.
