### ISSUE TITLE
How can I change the font size of the characters on the axes?

### ISSUE THREAD

**Issue by LakeRainSound** [gavinsimpson/gratia#91]
Thank you for the wonderful package.
When the figure is exported after using `draw` function, the characters on the axes are too small to see, so I would like to know how to change the size of the letters on the axes.

**Comment by gavinsimpson** [comment]
This is likely an issue related to how you are using `ggsave()` and how large a file you are creating and what resolution it is being created with.

There isn't a way to modify the thematic elements of a set of plots created by `draw()`; if you want more control you need to use `evaluate_smooth()` or `smooth_estimates()` to evaluate  individual smooths and then you can add ` + theme(....)` to modify any of the elements of a ggplot theme, and then combine the plots with `cowplot::plot_grid()` or {patchwork}.
