### ISSUE TITLE
How can I change ylab title

### ISSUE THREAD

**Issue by IssamHu** [gavinsimpson/gratia#92]
Thank you for the wonderful package.
I'm using draw()  function and I want to change the ylab title from "Effect" to for example "Oxygen".

**Comment by gavinsimpson** [comment]
You will have to do some work yourself, but you can do

```r
es <- evaluate_smooth(gam_model, "s(foo)")
```

replacing `gam_model` with the name of your fitted GAM, and `"s(foo)"` with the name of the smooth you want to plot. And then plot `es` using **ggplot2** by hand. You can then use **cowplot** or **patchwork** packages to arrange the as many of these separate plots on a page as you want.

You can also do

```r
draw(evaluate_smooth(gam_model, "s(foo)"), ylab = "Oxygen")
```

If you just want to get what `draw()` is doing for the whole model but for the specified smooth.

**Comment by gavinsimpson** [comment]
If that doesn't help or answer your questions, reopen this issue and I can see about providing an example.
