### ISSUE TITLE
factor labels in draw(penalty()) are sorted lexicographically

### ISSUE THREAD

**Issue by tjmahr** [gavinsimpson/gratia#95]
![image](https://user-images.githubusercontent.com/1890315/105723687-af396880-5eec-11eb-8444-9f94dfe53ead.png)

I.e., the axis goes f1, f10, f11, f2, f3, ... if there are 11 factors. I would suggest padding 0s so they they sort correctly or using a factor()

**Comment by gavinsimpson** [comment]
Good catch; I might store the `row` and `col` as numeric in the object returned by `penalty()` and then do as you suggest and pad with 0 when I convert to the `fn` form.

**Comment by gavinsimpson** [comment]
Thanks @tjmahr; this is now fixed on GitHub:

![draw-penalty-df-issue-95-label-order](https://user-images.githubusercontent.com/514696/105751748-0c90e200-5f0c-11eb-8763-4fe39387285b.png)
