### ISSUE TITLE
`fun` argument to draw() having no effect

### ISSUE THREAD

**Issue by Aariq** [gavinsimpson/gratia#96]
The `fun` argument in `draw.gam()` doesn't seem to have an effect.  Could that be because the `tranfsorm_fun` function is registered to use method `"add_constant"` ?

https://github.com/gavinsimpson/gratia/blob/87269b322bd93f7a2a78f0dcb5cafe68eca9717a/R/utililties.R#L1020

``` r
library(gratia)
load_mgcv()

dat <- gamSim(1, n = 400, dist = "normal", scale = 2)
#> Gu & Wahba 4 term additive model
m1 <- gam(y ~ s(x0) + s(x1) + s(x2) + s(x3), data = dat, method = "REML")

draw(m1, select = 1)
```

![](https://i.imgur.com/SjF0FBO.png)

``` r
draw(m1, select = 1, fun = exp)
```

![](https://i.imgur.com/l7O62R1.png)

<sup>Created on 2021-02-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by gavinsimpson** [comment]
Yep, that's the right diagnosis; a copy paste bug. Will fix now.
